### ISSUE TITLE
Ubicación de archivos

### ISSUE THREAD

**Issue by Piarrot** [1022FSNSANCN02ARED/grupo-02#1]
Hola grupo! Les recomiendo que acomoden los archivos de la siguiente manera:

```
/(raiz del repo)
|- diseños  (todos los diseños del sprint 1)
|- readme.md
|- (el resto de los archivos del proyecto)
```

**Comment by BenRomeroArg** [comment]
Buenas, problema resuelto. Ademas agregamos una carpeta y metimos todos loa archivos y carpetas referidos al funcionamiento y ejecucion del proyecto, gracias!
