### ISSUE TITLE
Dependencia innecesaria

### ISSUE THREAD

**Issue by LuiosDyet** [1022FSNSANCN02ARED/grupo-02#2]
Ojo con las dependencias que instalan, porqué instalaron el paquete “modules”? Imagino que fue sin querer, si fue así borrenlo. 

https://github.com/1022FSNSANCN02ARED/grupo-02/blob/ccc56a559a9a1c9ed4ae5708b70370c773de6627/digitalstore/package.json#L7

**Comment by MelinaLeonardi** [comment]
corregido!
